# Generated by Django 4.1.3 on 2024-03-05 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StaffApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
