# Generated by Django 4.1.3 on 2023-09-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffApp', '0003_tag_alter_member_category_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Professor'), (2, 'Assoc. Professor'), (3, 'Assist. Professor'), (4, 'Postdoc'), (5, 'PhD Student'), (6, 'BSc Student'), (7, 'MSc Student')], null=True),
        ),
    ]
