# Generated by Django 4.1.3 on 2024-04-25 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StaffApp', '0006_location_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
    ]
